version: '3.9'

networks:
  iced-latte-network-qa:
    name: iced-latte-network-qa
    attachable: true

volumes:
  pg_data:
  nginx_data:
  minio_data:
  backend_logs: {}

services:
  iced-latte-backend-qa:
    image: 'zufarexplainedit/iced-latte-backend:${DOCKER_IMAGE_TAG}'
    container_name: iced-latte-backend-qa
    environment:
      APP_SERVER_PORT: 8083
      APP_JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      APP_JWT_REFRESH_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      DATASOURCE_PORT: 5432
      DATASOURCE_NAME: testdb
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      DATASOURCE_HOST: iced-latte-postgresdb-qa
      REDIS_HOST: iced-latte-redis
      REDIS_PORT: 6380
      MINIO_HOST: http://iced-latte-minio-qa
      MINIO_PORT: 9000
      MINIO_DEFAULT_PRODUCT_IMAGES_PATH: ./products
    ports:
      - '8083:8083'
      - '5005:5005'
    networks:
      - iced-latte-network-qa
    depends_on:
      - iced-latte-minio-qa
      - iced-latte-postgresdb-qa
    volumes:
      - backend_logs:/usr/app/logs
      - ./products:/usr/app/products
    restart: on-failure

  iced-latte-postgresdb-qa:
    image: 'postgres:13.11-bullseye'
    container_name: iced-latte-postgresdb-qa
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    networks:
      - iced-latte-network-qa
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure

  iced-latte-minio-qa:
    image: minio/minio
    container_name: iced-latte-minio-qa
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio123
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - iced-latte-network-qa
    command: server /data --console-address ":9001"
    restart: on-failure
